/**
 * Default LaTeX template — \documentclass, geometry, fonts, hyperref.
 * Foundations may override by passing a different `template` string
 * through `buildLatexOptions`. The default produces a 6×9 trade-book
 * shape with a generic serif font, suitable for casual book / monograph
 * / report output. The thesis-uoft kind (TF11b) ships its own
 * template.
 */

const DEFAULT_TRIM = { width: '6in', height: '9in', margin: '0.75in' }

function trimLine(trim) {
  const t = { ...DEFAULT_TRIM, ...(trim || {}) }
  return `\\usepackage[paperwidth=${t.width}, paperheight=${t.height}, margin=${t.margin}]{geometry}`
}

const DEFAULT_TEMPLATE = `% Default book-class template.
% Override by passing a custom \`template\` string via
% buildLatexOptions in the foundation's compile-options.js.
\\documentclass[11pt]{book}

\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}
${trimLine(null)}
\\usepackage{graphicx}
\\usepackage{xcolor}
\\usepackage{hyperref}
\\hypersetup{colorlinks=true, linkcolor=black, urlcolor=blue!50!black, citecolor=blue!50!black}

\\setcounter{tocdepth}{2}
\\setcounter{secnumdepth}{2}
`

export default DEFAULT_TEMPLATE

/**
 * Parameterised LaTeX template builder. Today consumes `trim`
 * (paperwidth / paperheight / margin) and `language` (passed to
 * `babel`). Future thesis-uoft variants override the entire string.
 */
export function createTemplate({ trim = null, language = 'en', covers = null } = {}) {
  // covers: thesis layouts may want a separate full-bleed cover image
  // page; the default template doesn't render covers (the Cover
  // section type emits its own \\chapter*-style title page). Accepted
  // here for API parity with typst-default's createTemplate.
  void covers

  const babelOpt = languageToBabel(language)
  return `% Auto-generated by @uniweb/book — default LaTeX template.
\\documentclass[11pt]{book}

\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}
${babelOpt ? `\\usepackage[${babelOpt}]{babel}` : ''}
${trimLine(trim)}
\\usepackage{graphicx}
\\usepackage{xcolor}
\\usepackage{csquotes}
\\usepackage{hyperref}
\\hypersetup{colorlinks=true, linkcolor=black, urlcolor=blue!50!black, citecolor=blue!50!black}

\\setcounter{tocdepth}{2}
\\setcounter{secnumdepth}{2}
`
}

// Map ISO-ish language tags to babel option names. Default: english.
// Foundations supporting more locales extend this map.
function languageToBabel(language) {
  if (!language) return 'english'
  const lang = String(language).toLowerCase()
  const MAP = {
    en: 'english',
    'en-us': 'american',
    'en-gb': 'british',
    fr: 'french',
    de: 'german',
    es: 'spanish',
    it: 'italian',
    pt: 'portuguese',
    ja: 'japanese',
    zh: 'chinese',
  }
  return MAP[lang] || MAP[lang.split('-')[0]] || 'english'
}
