// Materialize a `document.yml` for a bare folder of markdown.
//
// `unipress compile <dir>` requires a top-level config file (document.yml
// or site.yml). When a user points it at a plain folder of markdown — no
// config, content possibly loose at the root rather than under content/ —
// the CLI offers to generate a document.yml here, then compiles. This
// module owns the detection + file generation; the interactive offer
// itself lives in commands/compile.js (a CLI concern).
//
// Chapter discovery mirrors @uniweb/build's content-collector so the
// generated `content:` reading order matches what the collector will
// actually discover at compile time. The collector stays authoritative —
// the list we emit is a convenience manifest (and the trailing `...`
// keeps it forgiving), so faithful-but-not-identical is fine. The rules
// copied here: skip non-.md, `_`-prefixed (drafts), `@`-prefixed (nested
// child sections), and README.md; sort by numeric prefix; strip the
// numeric prefix to form the stable name used for ordering. Source of
// truth: framework/build/src/site/content-collector.js
// (isMarkdownFile / isChildSection / parseNumericPrefix / compareFilenames).

import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, parse } from 'node:path'
import { CONFIG_FILE_NAMES } from './document-yml.js'

// A markdown file that becomes a chapter/page (not a draft, nested child,
// or repo README).
function isChapterFile(filename) {
  if (!filename.endsWith('.md')) return false
  if (filename.startsWith('_')) return false
  if (filename.startsWith('@')) return false
  if (filename.toLowerCase() === 'readme.md') return false
  return true
}

function parseNumericPrefix(name) {
  const match = name.match(/^(\d+(?:\.\d+)*)-?(.*)$/)
  if (match) return { prefix: match[1], name: match[2] || match[1] }
  return { prefix: null, name }
}

// Sort by numeric prefix (dots are sub-levels: 1, 1.5, 2), unprefixed
// names last in locale order.
function compareFilenames(a, b) {
  const { prefix: pa } = parseNumericPrefix(parse(a).name)
  const { prefix: pb } = parseNumericPrefix(parse(b).name)
  if (!pa && !pb) return a.localeCompare(b)
  if (!pa) return 1
  if (!pb) return -1
  const partsA = pa.split('.').map(Number)
  const partsB = pb.split('.').map(Number)
  for (let i = 0; i < Math.max(partsA.length, partsB.length); i++) {
    const numA = partsA[i] ?? 0
    const numB = partsB[i] ?? 0
    if (numA !== numB) return numA - numB
  }
  return 0
}

function stableName(fileBase) {
  return parseNumericPrefix(fileBase).name
}

// Ordered stable chapter names for a directory (empty if none / unreadable).
function listChapters(dirPath) {
  let entries
  try {
    entries = readdirSync(dirPath)
  } catch {
    return []
  }
  return entries
    .filter(isChapterFile)
    .sort(compareFilenames)
    .map((f) => stableName(parse(f).name))
}

/**
 * Find where a bare folder keeps its markdown.
 *
 * Prefers an existing content/ then pages/ subfolder (the document.yml
 * profile default + its legacy fallback), else loose markdown at the
 * root. Returns the directory to point the collector at and the ordered
 * chapter names, or null when no markdown is found anywhere.
 *
 * @param {string} sitePath - Absolute path to the content directory.
 * @returns {{ contentDir: '.' | 'content' | 'pages', chapters: string[] } | null}
 */
export function detectBareContent(sitePath) {
  for (const dir of ['content', 'pages']) {
    const p = join(sitePath, dir)
    if (existsSync(p) && statSync(p).isDirectory()) {
      const chapters = listChapters(p)
      if (chapters.length) return { contentDir: dir, chapters }
    }
  }
  const rootChapters = listChapters(sitePath)
  if (rootChapters.length) return { contentDir: '.', chapters: rootChapters }
  return null
}

/**
 * Build a document.yml as a commented YAML string.
 *
 * Emits `paths: { pages: . }` only for root-level content; the book block
 * only for the book foundation. Comments explain the reading order and how
 * to edit, matching the style of the bundled templates' document.yml.
 *
 * @returns {string}
 */
export function buildDocumentYml({
  name,
  foundationRef,
  format,
  contentDir,
  chapters = [],
  author = ''
}) {
  const q = (s) => JSON.stringify(String(s ?? ''))
  const isBook = String(foundationRef).startsWith('@uniweb/book')
  const lines = [
    '# Generated by `unipress compile`. Edit freely — this is an ordinary',
    '# unipress document config. Docs: https://github.com/uniweb/unipress',
    '',
    `name: ${q(name)}`,
    `foundation: ${q(foundationRef)}`,
    `format: ${format}`
  ]
  if (contentDir === '.') {
    lines.push(
      '',
      '# Your markdown lives at the project root (no content/ or pages/',
      '# subfolder), so point the content directory at the root.',
      'paths:',
      '  pages: .'
    )
  }
  if (isBook) {
    lines.push('', 'book:', `  title: ${q(name)}`, `  author: ${q(author)}`, '  language: en')
  }
  if (chapters.length) {
    lines.push(
      '',
      '# Reading order. Each name is a chapter filename with any leading',
      '# "NN-" number prefix removed (00-intro.md → intro). Reorder these',
      '# lines to reorder the document; `...` includes anything you add',
      '# later. README.md is skipped automatically.',
      'content:'
    )
    for (const c of chapters) lines.push(`  - ${c}`)
    lines.push('  - ...')
  }
  lines.push('')
  return lines.join('\n')
}

/**
 * Write a generated document.yml into sitePath.
 *
 * @returns {{ path: string, content: string }}
 */
export function materializeDocumentYml({ sitePath, ...opts }) {
  const content = buildDocumentYml(opts)
  const path = join(sitePath, CONFIG_FILE_NAMES.PRIMARY)
  writeFileSync(path, content, 'utf8')
  return { path, content }
}
