// Scaffold a content directory from a unipress template.
//
// Templates live on disk under `framework/unipress/templates/<name>/` and
// are embedded into the bundle via `src/templates-data.js` (generated by
// scripts/generate-templates-data.js). This module reads from the embedded
// map — so scaffolding works identically in Node dev and inside the
// bun-compiled binary (which has no access to the templates/ path).
//
// Files with a `.hbs` suffix get Handlebars-processed (and the suffix
// stripped); everything else is copied verbatim. No package.json is
// written — unipress projects are content-only.
//
// Variables available in `.hbs` files:
//   title, author, year, date, foundation

import { readdir, mkdir, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import Handlebars from 'handlebars'
import { TemplateError } from './errors.js'
import { TEMPLATES } from './templates-data.js'

export async function scaffold({ templateName, targetDir, vars, force = false, onProgress = () => {} }) {
  const files = TEMPLATES[templateName]
  if (!files) {
    throw new TemplateError(
      `template not found: '${templateName}'\n` +
      `hint: run 'unipress list-templates' to see available templates`
    )
  }
  if (existsSync(targetDir) && (await readdir(targetDir)).length > 0 && !force) {
    throw new TemplateError(
      `target directory is not empty: ${targetDir}\n` +
      `hint: pick a different directory, or pass --force to overwrite`
    )
  }
  await mkdir(targetDir, { recursive: true })

  for (const [relPath, content] of Object.entries(files)) {
    let dstRel = relPath
    let dstContent = content
    if (relPath.endsWith('.hbs')) {
      dstRel = relPath.slice(0, -'.hbs'.length)
      dstContent = Handlebars.compile(content, { noEscape: true })(vars)
    }
    const dstPath = join(targetDir, dstRel)
    await mkdir(dirname(dstPath), { recursive: true })
    await writeFile(dstPath, dstContent)
    onProgress(relPath.endsWith('.hbs') ? `rendered ${dstRel}` : `copied   ${dstRel}`)
  }
}
