// Scaffold a content directory from a unipress template.
//
// Templates live on disk under `framework/unipress/documents/<name>/` and
// are embedded into the bundle via `src/templates-data.js` (generated by
// scripts/generate-templates-data.js). This module reads from the embedded
// map — so scaffolding works identically in Node dev and inside the
// bun-compiled binary (which has no access to the documents/ path).
//
// File entries come in two shapes:
//   - text files: a plain string. Files with a `.hbs` suffix get
//     Handlebars-processed (and the suffix stripped); other text files
//     are copied verbatim.
//   - binary files (PNG, PDF, fonts, archives, etc.): an object
//     `{ encoding: 'base64', content: <base64> }`. The generator detects
//     these by extension. Scaffold decodes and writes the bytes verbatim;
//     no Handlebars pass.
//
// No package.json is written — unipress projects are content-only.
//
// Handlebars variables available in `.hbs` files:
//   title, author, year, date, foundation

import { readdir, mkdir, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import Handlebars from 'handlebars'
import { TemplateError } from './errors.js'
import { TEMPLATES } from './templates-data.js'

export async function scaffold({ templateName, targetDir, vars, force = false, onProgress = () => {} }) {
  const files = TEMPLATES[templateName]
  if (!files) {
    throw new TemplateError(
      `template not found: '${templateName}'\n` +
      `hint: run 'unipress list-templates' to see available templates`
    )
  }
  if (existsSync(targetDir) && (await readdir(targetDir)).length > 0 && !force) {
    throw new TemplateError(
      `target directory is not empty: ${targetDir}\n` +
      `hint: pick a different directory, or pass --force to overwrite`
    )
  }
  await mkdir(targetDir, { recursive: true })

  for (const [relPath, entry] of Object.entries(files)) {
    let dstRel = relPath
    let dstContent
    let label
    if (entry !== null && typeof entry === 'object' && entry.encoding === 'base64') {
      dstContent = Buffer.from(entry.content, 'base64')
      label = 'extracted'
    } else if (relPath.endsWith('.hbs')) {
      dstRel = relPath.slice(0, -'.hbs'.length)
      dstContent = Handlebars.compile(entry, { noEscape: true })(vars)
      label = 'rendered'
    } else {
      dstContent = entry
      label = 'copied'
    }
    const dstPath = join(targetDir, dstRel)
    await mkdir(dirname(dstPath), { recursive: true })
    await writeFile(dstPath, dstContent)
    onProgress(`${label} ${dstRel}`)
  }
}
